# Configuration file for app engine

application: helloworld-aldrin
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /docs
  static_dir: docs
- url: /scripts
  static_dir: scripts

- url: /.*
  script: helloworld.application

- url: /_ah/mail/.+
  script: helloworld.application
  login: admin

inbound_services:
- mail

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest
